# Generated by Django 3.1.2 on 2020-11-26 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_movie_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MOVIE_DATA',
        ),
    ]
